In [1]:
import numpy as np
import torch

In [3]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear regression

In [5]:
w = torch.randn(2, 3, requires_grad=True)   ##weight
b = torch.randn(2, requires_grad=True)      ##bias
print(w)
print(b)

tensor([[ 0.0046, -0.0170,  0.0454],
        [ 0.6504,  1.9657,  0.4783]], requires_grad=True)
tensor([-0.6204,  0.9597], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b    ## @ 는 행렬 곱을 나타내고 t는 행렬 transpose

In [7]:
preds = model(inputs)
print(preds)

tensor([[5.2986e-01, 2.0071e+02],
        [1.2095e+00, 2.6374e+02],
        [1.3472e-01, 3.4870e+02],
        [8.0061e-01, 1.6953e+02],
        [1.2437e+00, 2.6803e+02]], grad_fn=<AddBackward0>)


In [8]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
#MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()    ## nemul : tensor내 elements 수

In [10]:
loss = mse(preds, targets)
print(loss)

tensor(16424.3730, grad_fn=<DivBackward0>)


In [11]:
loss.backward()

In [12]:
print(w)
print(w.grad)

tensor([[ 0.0046, -0.0170,  0.0454],
        [ 0.6504,  1.9657,  0.4783]], requires_grad=True)
tensor([[-6167.0117, -7469.2383, -4458.6626],
        [13383.5078, 14397.5078,  8776.3770]])


In [13]:
with torch.no_grad():       ## pytorch가 weight, bias 업데이트 하는동안 계산을 추적하거나 변형하지 않도록하는
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [15]:
loss = mse(preds, targets)
print(loss)   

tensor(16424.3730, grad_fn=<DivBackward0>)


In [16]:
## gradient 0으로 리셋
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


# Training using gradient descent

In [17]:
preds = model(inputs)
print(preds)

tensor([[ 11.9541, 177.5190],
        [ 16.2487, 233.2753],
        [ 18.0956, 312.6674],
        [ 11.9532, 146.4342],
        [ 15.7913, 238.8277]], grad_fn=<AddBackward0>)


In [18]:
loss = mse(preds, targets)
print(loss)

tensor(11169.2773, grad_fn=<DivBackward0>)


In [19]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-4985.7163, -6194.8862, -3673.3713],
        [10989.4805, 11825.7139,  7189.3301]])
tensor([-61.3914, 129.7447])


In [20]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [21]:
print(w)
print(b)

tensor([[0.1162, 0.1196, 0.1267],
        [0.4067, 1.7035, 0.3186]], requires_grad=True)
tensor([-0.6190,  0.9568], requires_grad=True)


In [22]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(7626.8564, grad_fn=<DivBackward0>)


# Train for multiple epochs

In [23]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [24]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss) ## Loss가 굉장히 많이 줄어든 모습

tensor(118.1221, grad_fn=<DivBackward0>)


# Using neural networks

In [25]:
import torch.nn as nn

In [26]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [27]:
from torch.utils.data import TensorDataset      ##tensor를 감싸는 dataset, tuple 처럼 input과 target에서 row단위로 접근가능

In [28]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [29]:
from torch.utils.data import DataLoader     ## data를 batch단위로 나눠줌, data 다루는 여러가지 기술 가짐

In [30]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [31]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[103.,  43.,  36.],
        [ 91.,  88.,  64.],
        [ 68.,  97.,  70.],
        [ 73.,  67.,  43.],
        [ 87., 135.,  57.]])
tensor([[ 20.,  38.],
        [ 81., 101.],
        [102., 120.],
        [ 56.,  70.],
        [118., 134.]])


In [32]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1354,  0.0644, -0.2186],
        [ 0.5407,  0.4817, -0.0364]], requires_grad=True)
Parameter containing:
tensor([-0.2217,  0.4046], requires_grad=True)


In [34]:
list(model.parameters())    ## weight와 bias의 모든 파라미터 알려줌

[Parameter containing:
 tensor([[-0.1354,  0.0644, -0.2186],
         [ 0.5407,  0.4817, -0.0364]], requires_grad=True),
 Parameter containing:
 tensor([-0.2217,  0.4046], requires_grad=True)]

In [35]:
preds = model(inputs)
preds

tensor([[-15.1889,  70.5869],
        [-20.8633,  89.6710],
        [-16.0480, 109.8855],
        [-19.3498,  74.9260],
        [-18.6806,  81.4097],
        [-15.3887,  70.6459],
        [-21.1462,  89.1529],
        [-16.4020, 110.3898],
        [-19.1500,  74.8670],
        [-18.7638,  80.8325],
        [-15.4719,  70.0687],
        [-21.0631,  89.7301],
        [-15.7651, 110.4036],
        [-19.2666,  75.5032],
        [-18.4808,  81.3506]], grad_fn=<AddmmBackward0>)

In [36]:
import torch.nn.functional as F
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(5356.4556, grad_fn=<MseLossBackward0>)


In [37]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [38]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()      ## 파라미터 업데이트
            opt.zero_grad() ## gradient 리셋

        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [39]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 643.5638
Epoch [20/100], Loss: 270.8579
Epoch [30/100], Loss: 194.0569
Epoch [40/100], Loss: 129.5916
Epoch [50/100], Loss: 60.7525
Epoch [60/100], Loss: 135.9795
Epoch [70/100], Loss: 45.0490
Epoch [80/100], Loss: 37.5162
Epoch [90/100], Loss: 59.1681
Epoch [100/100], Loss: 45.9646


In [40]:
preds = model(inputs)
preds

tensor([[ 58.1061,  71.9144],
        [ 79.5881,  96.5967],
        [121.6186, 138.8394],
        [ 27.6402,  46.0739],
        [ 93.6036, 106.9024],
        [ 56.9533,  70.9154],
        [ 78.9386,  95.9167],
        [121.6787, 139.0586],
        [ 28.7930,  47.0729],
        [ 94.1070, 107.2215],
        [ 57.4566,  71.2344],
        [ 78.4353,  95.5977],
        [122.2680, 139.5194],
        [ 27.1369,  45.7549],
        [ 94.7564, 107.9015]], grad_fn=<AddmmBackward0>)